export default {
  GET_SPRINTS: 'GET_SPRINTS',
  SET_SPRINTS: 'SET_SPRINTS',
  SWITCH_SPRINT: 'SWITCH_SPRINT',
  CHANGE_SORT_ORDER: 'CHANGE_SORT_ORDER',
  SET_SORT_ORDER: 'SET_SORT_ORDER',
  CHANGE_TASK_STATUS: 'CHANGE_TASK_STATUS',
  SET_TASK_STATUS: 'SET_TASK_STATUS',
  OPEN_TASK_ADD: 'OPEN_TASK_ADD',
  CLOSE_TASK_ADD: 'CLOSE_TASK_ADD',
  ADD_TASKS: 'ADD_TASKS',
  SET_ADDED_TASKS: 'SET_ADDED_TASKS'

}
