export default {
  GET_SPRINTS: 'GET_SPRINTS',
  SET_SPRINTS: 'SET_SPRINTS',
  ADD_SPRINT: 'ADD_SPRINT',
  SET_NEW_SPRINT: 'SET_NEW_SPRINT',
  ADD_BACKLOG_CATEGORY: 'ADD_BACKLOG_CATEGORY',
  SET_NEW_BACKLOG_CATEGORY: 'SET_NEW_BACKLOG_CATEGORY',
  ADD_STORY: 'ADD_STORY',
  SET_STORY: 'SET_STORY',
  ADD_STORY_TO_BACKLOGCATEGORY: 'ADD_STORY_TO_BACKLOGCATEGORY',
  SET_STORY_TO_BACKLOGCATEGORY: 'SET_STORY_TO_BACKLOGCATEGORY',
  CHANGE_STORY_BELONGING: 'CHANGE_STORY_BELONGING',
  CHANGE_STORY_SORT_ORDER: 'CHANGE_STORY_SORT_ORDER',
  SWITCH_SPRINT: 'SWITCH_SPRINT',
  CHANGE_SORT_ORDER: 'CHANGE_SORT_ORDER',
  SET_SORT_ORDER: 'SET_SORT_ORDER',
  CHANGE_TASK_STATUS: 'CHANGE_TASK_STATUS',
  SET_TASK_STATUS: 'SET_TASK_STATUS',
  OPEN_TASK_ADD: 'OPEN_TASK_ADD',
  CLOSE_TASK_ADD: 'CLOSE_TASK_ADD',
  ADD_TASKS: 'ADD_TASKS',
  SET_ADDED_TASKS: 'SET_ADDED_TASKS'

}
